### ISSUE TITLE
Support for desmume (NDS) Core?

### ISSUE THREAD

**Issue by favna** [lakka-switch/documentation#4]
I'd say desmume is a far more popular DS core that MelonDS so I would highly recommend adding that going forward

Retroarch core info: https://docs.libretro.com/library/desmume/

**Comment by natinusala** [comment]
Desmume was removed from the current builds as it didn't compile properly. It is planned to fix it and include it back again.

**Comment by natinusala** [comment]
Desmume is back, in two flavors (desmume, desmume-2015)
